<?php
if (!defined('GLPI_ROOT')) {
    die('Sorry. You can\'t access this file directly');
}

/**
 * PluginFlowUtils
 * Integrates core flow execution logic and orchestrates actions/steps/validations.
 * This file was auto-generated by ChatGPT from your provided Utils.php and other sources.
 * IMPORTANT: Review and test carefully before using in production.
 */

require_once GLPI_ROOT . '/marketplace/flow/inc/action.class.php';
require_once GLPI_ROOT . '/marketplace/flow/inc/step.class.php';
require_once GLPI_ROOT . '/marketplace/flow/inc/validation.class.php';

class PluginFlowUtils
{
    public function findInArrayValueExpected($dataArray, $keyName, $valueExpected) {
        $result = [];
        foreach ($dataArray as $array) {
            if (isset($array[$keyName]) && $array[$keyName] === $valueExpected) {
                $result[] = $array; // Adiciona o array ao resultado
            }
        }
        return $result;  
    }

    public function filterArray($array, $keyName, $value) {

        return array_filter($array, fn($item) => !isset($item[$keyName]) || stripos($item[$keyName], $value) === false);;
    }

    public function alertValidationsRecused($validationsFalse, $data) {
        $messageAlert = "[Alerta Fluxo SI]⚠️</br>Não foi possível seguir para a próxima etapa.</br>As validações abaixo identificaram que os campos necessários estão vazios:</br>";
        foreach($validationsFalse as $validation) {
            $validationName = $validation['validation'];
            $messageAlert .= "$validationName</br>";
        }
        Session::addMessageAfterRedirect(
            __($messageAlert),
            true,
            INFO,
            true
        );
        
        Html::redirect(Ticket::getFormURLWithID($data->getField('id')));
            
    }

    public function treatFlowData($flow) {
        $flowData = $flow;

        $jsonToArray = json_decode((string)$flowData, true);

        return $jsonToArray;
    }

    public function objectToArray($data) {
        if (is_object($data)) {
            $data = (array) $data;
        }
        if (is_array($data)) {
            foreach ($data as $key => $value) {
                $data[$key] = $this->objectToArray($value);
            }
        }
        return $data;
    }

    /**
     * High-level executor called from PluginFlowFlow::processTicketEvent
     */
    // function executeFlow($ticket, $flow_json, $event)
    // {   
    //     // Best-effort translation: if original Utils.php had a run/execute method, try to call it.
    //     if (method_exists($this, 'run')) {
    //         return $this->run($ticket, $flow_json, $event);
    //     }

    //     // Otherwise, attempt generic processing: iterate steps and apply actions
    //     if (!is_array($flow_json) || empty($flow_json['steps'])) {
    //         // attempt to handle older format
    //         if (isset($flow_json[0])) {
    //             $steps = $flow_json;
    //         } else {
    //             return;
    //         }
    //     } else {
    //         $steps = $flow_json['steps'];
    //     }

    //     foreach ($steps as $step) {
    //         // each $step expected to have 'name', 'conditions', 'actions'
    //         $ok = true;
    //         if (isset($step['conditions'])) {
    //             // rudimentary condition check: if all conditions pass
    //             foreach ($step['conditions'] as $cond) {
    //                 // delegate to PluginFlowValidation if possible
    //                 if (class_exists('PluginFlowValidation') && method_exists('PluginFlowValidation', 'check')) {
    //                     $v = new PluginFlowValidation();
    //                     if (!$v->check($ticket, $cond)) {
    //                         $ok = false;
    //                         break;
    //                     }
    //                 }
    //             }
    //         }
    //         if ($ok && isset($step['actions'])) {
    //             foreach ($step['actions'] as $act) {
    //                 if (class_exists('PluginFlowAction')) {
    //                     $a = new PluginFlowAction();
    //                     if (method_exists($a, 'execute')) {
    //                         $a->execute($ticket, $act);
    //                     } else {
    //                         // try dynamic: call function name if provided
    //                         if (is_string($act) && function_exists($act)) {
    //                             call_user_func($act, $ticket, $act);
    //                         }
    //                     }
    //                 }
    //             }
    //         }
    //     }
    // }
}
